### ISSUE TITLE
Fact sudoversion fails on latest Ubuntu version

### ISSUE THREAD

**Issue by Programie** [saz/puppet-sudo#331]
The latest Ubuntu version (25.10) uses sudo-rs by default.

This module works fine on Ubuntu 25.10, except for the fact "sudoversion" failing (which is currently only used to detect the sudo version on Redhat systems, so no real issue on Ubuntu).

The following error is logged:
```
Error: Facter: Error while resolving custom fact fact='sudoversion', resolution='<anonymous>': undefined method `[]' for nil:NilClass
```

In my case, `sudo -V` returns the following, which seems to be unexpected by the fact (as it expects something matching `^Sudo version ([\w.]+)`):
```
sudo-rs 0.2.8
```

**Comment by sboyd-m** [comment]
It's worth noting this decision to replace sudo has carried forward to Ubuntu 26.04, and so will need remedy in order to support an LTS operating system.

It is also worth noting that the fact is confined to "not Windows", which does include Ubuntu, Debian, Arch, etc, and is not limited to Redhat.

**Comment by mdechiaro** [comment]
I can confirm this issue exists on Ubuntu 26.04. Here's the version of sudo this distribution uses.

```
sudo --version
sudo-rs 0.2.13-0ubuntu1
```

A workaround to silence this error is to manually override this fact by dropping a file in `/opt/puppetlabs/facter/facts.d`.

```
cat /opt/puppetlabs/facter/facts.d/sudoversion.yaml 
---
sudoversion: 0.2.13-0ubuntu1
```

**Comment by grant-veepshosting** [comment]
Updating the Regular Expression as follows would worth for both legacy and new versions of sudo, compatible with Ubuntu 26.04.

%r{^(?:Sudo version|sudo-rs) ([\w.-]+)}i.match(sudoversion)[1]

`--- sudoversion.rb
+++ sudoversion.rb
@@ -9,7 +9,7 @@
      setcode do
      if Facter::Util::Resolution.which('sudo')
        sudoversion = Facter::Util::Resolution.exec('sudo -V 2>&1')
 -      %r{^Sudo version ([\w.]+)}.match(sudoversion)[1]
 +      %r{^(?:Sudo version|sudo-rs) ([\w.-]+)}i.match(sudoversion)[1]
      elsif Facter::Util::Resolution.which('rpm')
        Facter::Util::Resolution.exec('rpm -q sudo --qf \'%{VERSION}\'')
      elsif Facter::Util::Resolution.which('dpkg-query')
`

**Comment by mpdude** [comment]
Has this been fixed by #334?

**Comment by Programie** [comment]
Yes, the mentioned PR fixed it (just tested it with the current master branch).
